POST http://localhost:3009/api/shorten HTTP/1.1
Content-Type: application/json

{
  "originalUrl":  "https://developer.typeform.com/create/reference/create-form",
  "expirationDate": 1639653300315
}

###
GET http://localhost:3009/api/ajsdhu HTTP/1.1