POST http://localhost:3009/api/shorten HTTP/1.1
Content-Type: application/json

{
  "originalUrl":  "https://github.com/alemaocastro1986/url-shortener",
  "expirationDate": 1639656900872
}

###
GET http://localhost:3009/api/ajsdhu HTTP/1.1